In [5]:
#6.rows and column-operations(add,update,delete)
data = {
    'Name':['Bishwas','Vishika','lalita','Rohit'],
    'Age':[16,11,22,33],
    'salary':[30000,300000,400000,50000]

}
import pandas as pd

In [6]:
df= pd.DataFrame(data)
print(df)

      Name  Age  salary
0  Bishwas   16   30000
1  Vishika   11  300000
2   lalita   22  400000
3    Rohit   33   50000

In [7]:
#add new column
df['team']=['CEO','HR','CTO','DA']
df

      Name  Age  salary team
0  Bishwas   16   30000  CEO
1  Vishika   11  300000   HR
2   lalita   22  400000  CTO
3    Rohit   33   50000   DA

In [8]:
df['bonus']= df['salary']*0.2
df

      Name  Age  salary team    bonus
0  Bishwas   16   30000  CEO   6000.0
1  Vishika   11  300000   HR  60000.0
2   lalita   22  400000  CTO  80000.0
3    Rohit   33   50000   DA  10000.0

In [9]:
#add new row
df.loc[len(df)] = ['ABC',21,30000,'BA',40000]
df

      Name  Age  salary team    bonus
0  Bishwas   16   30000  CEO   6000.0
1  Vishika   11  300000   HR  60000.0
2   lalita   22  400000  CTO  80000.0
3    Rohit   33   50000   DA  10000.0
4      ABC   21   30000   BA  40000.0

In [10]:
#update value
df.loc[0,'salary']=50000
df

      Name  Age  salary team    bonus
0  Bishwas   16   50000  CEO   6000.0
1  Vishika   11  300000   HR  60000.0
2   lalita   22  400000  CTO  80000.0
3    Rohit   33   50000   DA  10000.0
4      ABC   21   30000   BA  40000.0

In [11]:
df.loc[df.Name =='Bishwas','salary']=40000
df

      Name  Age  salary team    bonus
0  Bishwas   16   40000  CEO   6000.0
1  Vishika   11  300000   HR  60000.0
2   lalita   22  400000  CTO  80000.0
3    Rohit   33   50000   DA  10000.0
4      ABC   21   30000   BA  40000.0

In [12]:
#delete value
df.drop('bonus',axis=1,inplace=True)   #drop cloumn
df

      Name  Age  salary team
0  Bishwas   16   40000  CEO
1  Vishika   11  300000   HR
2   lalita   22  400000  CTO
3    Rohit   33   50000   DA
4      ABC   21   30000   BA

In [14]:
df=df.drop(df[df.Name == 'ABC'].index) #drop row
df

      Name  Age  salary team
0  Bishwas   16   40000  CEO
1  Vishika   11  300000   HR
2   lalita   22  400000  CTO
3    Rohit   33   50000   DA

In [15]:
#df.drop(['Bonus','Team'],axis=1)   to delete multiple column

In [16]:
#sort values
df.sort_values('salary')  #ascending order

      Name  Age  salary team
0  Bishwas   16   40000  CEO
3    Rohit   33   50000   DA
1  Vishika   11  300000   HR
2   lalita   22  400000  CTO

In [19]:
df.sort_values('salary', ascending=False)  #descending order

      Name  Age  salary team
2   lalita   22  400000  CTO
1  Vishika   11  300000   HR
3    Rohit   33   50000   DA
0  Bishwas   16   40000  CEO

In [20]:
#7.  working with date values

In [21]:
df['DO']=['2026-01-01','2026-01-15','2026-02-02','2026-03-01']
df

      Name  Age  salary team          DO
0  Bishwas   16   40000  CEO  2026-01-01
1  Vishika   11  300000   HR  2026-01-15
2   lalita   22  400000  CTO  2026-02-02
3    Rohit   33   50000   DA  2026-03-01

In [22]:
df['DO'].dtype

dtype('O')

In [23]:
df['DO']=pd.to_datetime(df['DO'])

In [24]:
df['DO'].dtype

dtype('<M8[ns]')

In [25]:
df1=df

In [26]:
df1

      Name  Age  salary team         DO
0  Bishwas   16   40000  CEO 2026-01-01
1  Vishika   11  300000   HR 2026-01-15
2   lalita   22  400000  CTO 2026-02-02
3    Rohit   33   50000   DA 2026-03-01

In [27]:
df1['DO2']=['2025-01-01','2025-01-15','2025-02-02','2025-03-01']
df1

      Name  Age  salary team         DO         DO2
0  Bishwas   16   40000  CEO 2026-01-01  2025-01-01
1  Vishika   11  300000   HR 2026-01-15  2025-01-15
2   lalita   22  400000  CTO 2026-02-02  2025-02-02
3    Rohit   33   50000   DA 2026-03-01  2025-03-01

In [28]:
df1['DO2'].dtype

dtype('O')

In [29]:
df

      Name  Age  salary team         DO         DO2
0  Bishwas   16   40000  CEO 2026-01-01  2025-01-01
1  Vishika   11  300000   HR 2026-01-15  2025-01-15
2   lalita   22  400000  CTO 2026-02-02  2025-02-02
3    Rohit   33   50000   DA 2026-03-01  2025-03-01

In [30]:
df=df.drop('DO2',axis=1)

In [31]:
#extract year,month,week,day
df['DO'].dt.year

0    2026
1    2026
2    2026
3    2026
Name: DO, dtype: int32

In [32]:
df['DO'].dt.day

0     1
1    15
2     2
3     1
Name: DO, dtype: int32

In [33]:
df['DO'].dt.day_name()

0    Thursday
1    Thursday
2      Monday
3      Sunday
Name: DO, dtype: object

In [34]:
df['Month']=df['DO'].dt.month

In [35]:
df

      Name  Age  salary team         DO  Month
0  Bishwas   16   40000  CEO 2026-01-01      1
1  Vishika   11  300000   HR 2026-01-15      1
2   lalita   22  400000  CTO 2026-02-02      2
3    Rohit   33   50000   DA 2026-03-01      3

In [36]:
df['DO']+pd.Timedelta(days=90)

0   2026-04-01
1   2026-04-15
2   2026-05-03
3   2026-05-30
Name: DO, dtype: datetime64[ns]

In [37]:
#8.handling missing values

In [41]:
df.isnull()
import numpy as np

In [42]:
df.loc[df.Name=='Rohit','salary']= np.nan

In [43]:
df

      Name  Age    salary team         DO  Month
0  Bishwas   16   40000.0  CEO 2026-01-01      1
1  Vishika   11  300000.0   HR 2026-01-15      1
2   lalita   22  400000.0  CTO 2026-02-02      2
3    Rohit   33       NaN   DA 2026-03-01      3

In [44]:
df.isnull(

)

    Name    Age  salary   team     DO  Month
0  False  False   False  False  False  False
1  False  False   False  False  False  False
2  False  False   False  False  False  False
3  False  False    True  False  False  False

In [45]:
df.isnull().sum()

Name      0
Age       0
salary    1
team      0
DO        0
Month     0
dtype: int64

In [46]:
df.fillna(0)

      Name  Age    salary team         DO  Month
0  Bishwas   16   40000.0  CEO 2026-01-01      1
1  Vishika   11  300000.0   HR 2026-01-15      1
2   lalita   22  400000.0  CTO 2026-02-02      2
3    Rohit   33       0.0   DA 2026-03-01      3