In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [4]:
pd.__version__

'2.2.2'

In [9]:
#1 create dataframe
df = pd.DataFrame([11,22,33], columns=['col_Name'])
print(df)

   col_Name
0        11
1        22
2        33

In [10]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [14]:
data = {
    'Name':['Bishwas','Vishika','lalita','Rohit'],
    'Age':[16,11,22,33],
    'salary':[30000,300000,400000,50000]

}

In [15]:
df= pd.DataFrame(data)
print(df)

      Name  Age  salary
0  Bishwas   16   30000
1  Vishika   11  300000
2   lalita   22  400000
3    Rohit   33   50000

In [ ]:
#2.Basic DataFrame understanding

In [16]:
df.head(3)  #to print top rows

      Name  Age  salary
0  Bishwas   16   30000
1  Vishika   11  300000
2   lalita   22  400000

In [17]:
df.tail(2)

     Name  Age  salary
2  lalita   22  400000
3   Rohit   33   50000

In [18]:
df.shape

(4, 3)

In [19]:
df.columns

Index(['Name', 'Age', 'salary'], dtype='object')

In [22]:
#rename columns
df1=df.rename(columns={'salary':'Monthly_salary'})

In [23]:
df1

      Name  Age  Monthly_salary
0  Bishwas   16           30000
1  Vishika   11          300000
2   lalita   22          400000
3    Rohit   33           50000

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   salary  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [25]:
df.describe()

             Age         salary
count   4.000000       4.000000
mean   20.500000  195000.000000
std     9.469248  183757.086031
min    11.000000   30000.000000
25%    14.750000   45000.000000
50%    19.000000  175000.000000
75%    24.750000  325000.000000
max    33.000000  400000.000000

In [ ]:
#3.save and load data from csv

In [28]:
df.to_csv('test_data.csv',index='none')

In [29]:
load_df=pd.read_csv('test_data.csv')
load_df

   Unnamed: 0     Name  Age  salary
0           0  Bishwas   16   30000
1           1  Vishika   11  300000
2           2   lalita   22  400000
3           3    Rohit   33   50000

In [ ]:
#4.rows columns selection

In [30]:
df[['Name']]

      Name
0  Bishwas
1  Vishika
2   lalita
3    Rohit

In [32]:
df[['Name','salary']]

      Name  salary
0  Bishwas   30000
1  Vishika  300000
2   lalita  400000
3    Rohit   50000

In [34]:
df.loc[df.Name=='Bishwas']  #loc = label based index

      Name  Age  salary
0  Bishwas   16   30000

In [35]:
df.loc[(df.Name=='Bishwas') & (df.Age>15)]

      Name  Age  salary
0  Bishwas   16   30000

In [37]:
#iloc - index value based
df.iloc[0]
df.iloc[0:3]  #[start:stop:step]

      Name  Age  salary
0  Bishwas   16   30000
1  Vishika   11  300000
2   lalita   22  400000

In [38]:
#5.filter dataframe
df

      Name  Age  salary
0  Bishwas   16   30000
1  Vishika   11  300000
2   lalita   22  400000
3    Rohit   33   50000

In [39]:
df['Age']>15

0     True
1    False
2     True
3     True
Name: Age, dtype: bool

In [41]:
df[df['Age']>15]

      Name  Age  salary
0  Bishwas   16   30000
2   lalita   22  400000
3    Rohit   33   50000

In [43]:
df_age_filter=df[df['Age']>15]
df_age_filter

      Name  Age  salary
0  Bishwas   16   30000
2   lalita   22  400000
3    Rohit   33   50000

In [48]:
df[(df['Age'] >15) & (df['salary'] >=50000)]

     Name  Age  salary
2  lalita   22  400000
3   Rohit   33   50000

In [49]:
df.where(df['Age']>15 ,other='not eligible')

           Name           Age        salary
0       Bishwas            16         30000
1  not eligible  not eligible  not eligible
2        lalita            22        400000
3         Rohit            33         50000