In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
data = {
    'Name':['Bishwas','Vishika','lalita','Rohit'],
    'Age':[16,11,22,33],
    'salary':[30000,300000,400000,50000]

}
import pandas as pd

In [5]:
df= pd.DataFrame(data)
print(df)

      Name  Age  salary
0  Bishwas   16   30000
1  Vishika   11  300000
2   lalita   22  400000
3    Rohit   33   50000

In [ ]:
#9.Aggregration and Group by

In [6]:
df['Name'].value_counts()

Name
Bishwas    1
Vishika    1
lalita     1
Rohit      1
Name: count, dtype: int64

In [9]:
df[df['Name']=='Rohit'].value_counts()

Name   Age  salary
Rohit  33   50000     1
Name: count, dtype: int64

In [11]:
df.groupby('Name')['salary'].sum()

Name
Bishwas     30000
Rohit       50000
Vishika    300000
lalita     400000
Name: salary, dtype: int64

In [ ]:
#10.concatenate and merge Dataframe(joins)

In [14]:
df1=pd.DataFrame({'ID':[1,2,3,4],'Name':['A','B','C','D']})
df1

   ID Name
0   1    A
1   2    B
2   3    C
3   4    D

In [13]:
df2=pd.DataFrame({'ID':[1,2,2,4],'Score':[88,89,90,91]})
df2

   ID  Score
0   1     88
1   2     89
2   2     90
3   4     91

In [15]:
pd.concat([df1,df2],axis=0)  #vertical or row level join

   ID Name  Score
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
3   4    D    NaN
0   1  NaN   88.0
1   2  NaN   89.0
2   2  NaN   90.0
3   4  NaN   91.0

In [16]:
pd.concat([df1,df2],axis=1)   #column level join/horizontal

   ID Name  ID  Score
0   1    A   1     88
1   2    B   2     89
2   3    C   2     90
3   4    D   4     91

In [17]:
#merge=join
pd.merge(df1,df2,how='inner',on='ID')

   ID Name  Score
0   1    A     88
1   2    B     89
2   2    B     90
3   4    D     91

In [18]:
pd.merge(df1,df2,how='left',on='ID')

   ID Name  Score
0   1    A   88.0
1   2    B   89.0
2   2    B   90.0
3   3    C    NaN
4   4    D   91.0

In [19]:
pd.merge(df1,df2,how='inner', left_on='ID',right_on='ID' )

   ID Name  Score
0   1    A     88
1   2    B     89
2   2    B     90
3   4    D     91

In [20]:
#11. AI (using)